services:

  web:
    restart: always
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
      target: builder
    command: bash compose/local/django/start.sh
    working_dir: /app
    volumes:
      - ./:/app
      - /app/.venv
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:17.5
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data:
