# Generated by Django 5.2.3 on 2025-06-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TimeSlotSeries",
        ),
    ]
